"""更新 Start_Render.bat：使用动态生成的通知内容。

bat 必须保持**纯 ASCII**（2026-10-07 踩过编码坑：cmd 按 GBK 解析 UTF-8
中文会乱码刷屏）。所以：
    - bat 里不放任何中文
    - 通知的标题和正文由 tools/gen_restart_notify.py 生成到两个 UTF-8 文件
    - bat 用 curl 的 "title@文件" / "desp@文件" 语法读取
"""
import os
import shutil
import time

UP = r'F:\DanmakuRender_AutoUp'
BAT = os.path.join(UP, 'Start_Render.bat')

BAT_ASCII = r'''@echo off
rem ============================================================
rem  DanmakuRender launcher (ASCII only - DO NOT add non-ASCII!)
rem
rem  Why ASCII only:
rem    cmd.exe parses this file using the SYSTEM code page (936/GBK)
rem    BEFORE the chcp below takes effect. Any UTF-8 Chinese here
rem    would be misread as GBK and break command parsing, causing
rem    an endless flood of "not recognized as an internal command".
rem    Chinese notification text is generated by python into
rem    notify_title.txt / notify_content.txt instead.
rem ============================================================

rem chcp 65001 so curl sends UTF-8 bodies correctly
chcp 65001 >nul

title DanmakuRender_Guard

rem --- config ---
set "API_URL=https://17530.push.ft07.com/send/sctp17530thl3urer2dsbnw3rnqyxzep.send"
set "TITLE_FILE=F:\DanmakuRender_AutoUp\notify_title.txt"
set "CONTENT_FILE=F:\DanmakuRender_AutoUp\notify_content.txt"
rem ---------------

:loop
cls
echo [%date% %time%] Starting DanmakuRender ...

rem switch to project drive and dir first, so python can find things
F:
cd "F:\DanmakuRender_AutoUp"

rem Generate notification text (time / CD2 status / live count / flap warning).
rem   Failures here must NOT block startup, hence the redirect and no check.
".\.venv\Scripts\python.exe" tools\gen_restart_notify.py >nul 2>&1

rem Send notification.
rem   -m 15 : timeout, otherwise a stuck network blocks startup forever
rem   title@file / desp@file : read UTF-8 text from files
curl -s -m 15 --data-urlencode "title@%TITLE_FILE%" --data-urlencode "desp@%CONTENT_FILE%" "%API_URL%" >nul 2>&1

rem run in venv
rem   --quiet : keep all INFO (so you can see each streamer loading)
rem             but filter out the engine message-dict noise
".\.venv\Scripts\python.exe" main.py --quiet

echo.
echo [%date% %time%] WARNING: program exited (crash or manual close).
echo Restarting in 10 seconds ...
echo.

timeout /t 10
goto loop
'''

print('=' * 78)
print('1. 备份当前 bat')
print('=' * 78)
bk = BAT + '.bak-' + time.strftime('%Y%m%d-%H%M%S')
if os.path.exists(BAT):
    shutil.copy2(BAT, bk)
    print(f'  已备份 {os.path.basename(bk)}')

print()
print('=' * 78)
print('2. 写新 bat（强制 ASCII 校验）')
print('=' * 78)
try:
    with open(BAT, 'w', encoding='ascii', newline='\r\n') as f:
        f.write(BAT_ASCII)
    print('  ✅ 写入成功')
except UnicodeEncodeError as e:
    print(f'  ❌ 混入了非 ASCII 字符: {e}')
    raise SystemExit(1)

raw = open(BAT, 'rb').read()
na = len([b for b in raw if b > 127])
print(f'  非 ASCII 字节: {na}  {"✅" if na == 0 else "❌"}')
print(f'  含 --quiet:      {b"--quiet" in raw}')
print(f'  含 title@:       {b"title@%TITLE_FILE%" in raw}')
print(f'  含 desp@:        {b"desp@%CONTENT_FILE%" in raw}')
print(f'  含 gen_restart:  {b"gen_restart_notify.py" in raw}')

print()
print('=' * 78)
print('3. 内容预览')
print('=' * 78)
for i, l in enumerate(raw.decode('ascii').split('\r\n'), 1):
    if l.strip() and not l.strip().startswith('rem'):
        print(f'  {i:2}| {l}')
